version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - "443:443"
    restart: "always"
    volumes:
      - ./wordpress:/var/www/html:delegate
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    restart: "always"
    env_file:
      - .env
  db:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=wp
      - MYSQL_USER=wp
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
networks:
  inception:
    driver: bridge