version: '3'

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    ports:
      - "443:443"
    restart: "always"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - inception
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    restart: "always"
    env_file: ./.env
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
      - nginx
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/jvander-/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/jvander-/data/mariadb
      o: bind