--CREATE DATABASE $MARIABDB_NAME;
--CREATE USER '$MARIADB_USER' IDENTIFIED BY '$MARIADB_PASSWORD';
--GRANT ALL PRIVILEGES ON $MARIADB_NAME TO $MARIADB_USER;
--FLUSH PRIVILEGES;

CREATE DATABASE $MARIADB_NAME;
CREATE USER '$MARIADB_USER'@'%' IDENTIFIED by '$MARIADB_PWD';
GRANT ALL PRIVILEGES ON $MARIADB_NAME.* TO $MARIADB_USER@'%';
FLUSH PRIVILEGES;